apiVersion: v1
kind: Service
metadata:
  name: eck1-gateway
  labels:
    app: eck1-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app: eck1-gateway
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
