using Microsoft.CodeAnalysis;
using System.Text;

using static ECK1.CodeGen.Shared.Common.Common;
using static ECK1.CodeGen.Shared.Grpc.GrpcCommon;

namespace ECK1.GrpcService.Client.CodeGen;

[Generator]
public class ServiceAbstractionsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var symbolCollection  = GetTypesForCodeGenWithDepsByInterface(context, InterfaceName);

        var compilation = context.CompilationProvider;

        context.RegisterSourceOutput(compilation.Combine(symbolCollection), (spc, data) =>
        {
            try
            {
                var (comp, symbols) = data;

                if (!symbols.Any())
                    return;

                var existing = comp.GetTypeByMetadataName($"{NsPrefix}.Configuration.Generated.ConsumerConfigurator");

                if (existing != null)
                    return;

                GenerateFactory(spc, symbols);
                GenerateConfigurator(spc, symbols);

                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        id: "GEN003",
                        title: "Generator Executed",
                        messageFormat: $"ClientConsumerConfigurator executed. Found {symbols.Count()} classes.",
                        category: "Generator",
                        DiagnosticSeverity.Warning,
                        isEnabledByDefault: true),
                    Location.None));

                spc.AddSource("BuildTimeInfo.ClientConsumerConfigurator.g.cs", $"// Generated at {DateTime.Now}");
            }
            catch (Exception e)
            {
                spc.AddSource("Exception.ClientConsumerConfigurator.g.cs", "// <auto-generated/>\n\n" + e);
            }
        });
    }

    private void GenerateFactory(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();

        sb.AppendLine("using Grpc.Net.Client;");
        sb.AppendLine("using ProtoBuf.Grpc.Client;");
        sb.AppendLine("using System.Net;");
        sb.AppendLine();
        sb.AppendLine($"namespace {NsPrefix}.Generated;");
        sb.AppendLine();
        sb.AppendLine("// Auto-generated");
        sb.AppendLine("public static class EntityStoreGrpcServiceClientFactory");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEntityStoreGrpcService Create(string url)");
        sb.AppendLine("    {");
        sb.AppendLine("        // GrpcClientFactory.AllowUnencryptedHttp2 = true;");
        sb.AppendLine();
        sb.AppendLine("        var channel = GrpcChannel.ForAddress(url, new GrpcChannelOptions");
        sb.AppendLine("        {");
        sb.AppendLine("            HttpHandler = new SocketsHttpHandler");
        sb.AppendLine("            {");
        sb.AppendLine("                AllowAutoRedirect = false,");
        sb.AppendLine("                AutomaticDecompression = DecompressionMethods.None,");
        sb.AppendLine("                //EnableMultipleHttp2Connections = true");
        sb.AppendLine("            }");
        sb.AppendLine("        });");
        sb.AppendLine();
        sb.AppendLine("        return channel.CreateGrpcService<IEntityStoreGrpcService>();");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("EntityStoreGrpc.ClientFactory.g.cs", sb.ToString());
    }

    private void GenerateConfigurator(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"using {NsPrefix}.Generated;");
        sb.AppendLine($"using {NsPrefix}.CommonDto.Generated;");
        sb.AppendLine();
        sb.AppendLine($"namespace {NsPrefix}.Configuration.Generated;");
        sb.AppendLine();
        sb.AppendLine("// Auto-generated");
        sb.AppendLine("public static class ClientConsumerConfigurator");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddEventConsumers(string grpcServerUrl, AbstractClientConsumerConfigurator config)");
        sb.AppendLine("    {");
        sb.AppendLine("        var svc = EntityStoreGrpcServiceClientFactory.Create(grpcServerUrl);");
        sb.AppendLine();

        foreach (var t in symbols)
        {
            try
            {
                AppendConfigActionForType(t, sb);
            }
            catch (Exception ex)
            {
                spc.AddSource($"ClientConsumerConfigurator_ERR_{Guid.NewGuid():N}.g.cs",
                    $"// Service generator failed for {t?.ToDisplayString()}: {ex}");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public abstract class AbstractClientConsumerConfigurator");
        sb.AppendLine("{");
        sb.AppendLine("    public abstract void SetupConsumer<TContract>(");
        sb.AppendLine("        Func<GetEntityRequest<TContract>, ValueTask<EntityResponse<TContract>>> getter)");
        sb.AppendLine($"        where TContract : class, {InterfaceName};");
        sb.AppendLine("}");

        spc.AddSource("EntityStoreGrpc.ClientConsumerConfigurator.g.cs", sb.ToString());
    }

    private void AppendConfigActionForType(INamedTypeSymbol classSymbol, StringBuilder sb)
    {
        var safeId = MakeSafeIdentifier(classSymbol);
        var typeText = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"        config.SetupConsumer<{typeText}>(");
        sb.AppendLine($"            svc.{BuildGrpcGetEntityMethodName(safeId)});");
    }
}
