// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.1+9110c693767c1dde2665b2b57939333478b12036
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ECK1.IntegrationContracts.Kafka.IntegrationRecords.Generated
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using global::Avro;
    using global::Avro.Specific;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.1+9110c693767c1dde2665b2b57939333478b12036")]
    public partial class ThinEvent : global::Avro.Specific.ISpecificRecord
    {
        public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""ThinEvent"",""namespace"":""ECK1.IntegrationContracts.Kafka.IntegrationRecords"",""fields"":[{""name"":""EntityId"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""EventId"",""type"":{""type"":""string"",""logicalType"":""uuid""}},{""name"":""EventType"",""type"":""string""},{""name"":""OccuredAt"",""type"":{""type"":""long"",""logicalType"":""timestamp-millis""}},{""name"":""Targets"",""default"":null,""type"":[""null"",{""type"":""array"",""items"":""string""}]},{""name"":""Version"",""type"":""int""}]}");
        private System.Guid _EntityId;
        private System.Guid _EventId;
        private string _EventType;
        private System.DateTime _OccuredAt;
        private IList<System.String> _Targets;
        private int _Version;
        public virtual global::Avro.Schema Schema
        {
            get
            {
                return ThinEvent._SCHEMA;
            }
        }
        public System.Guid EntityId
        {
            get
            {
                return this._EntityId;
            }
            set
            {
                this._EntityId = value;
            }
        }
        public System.Guid EventId
        {
            get
            {
                return this._EventId;
            }
            set
            {
                this._EventId = value;
            }
        }
        public string EventType
        {
            get
            {
                return this._EventType;
            }
            set
            {
                this._EventType = value;
            }
        }
        public System.DateTime OccuredAt
        {
            get
            {
                return this._OccuredAt;
            }
            set
            {
                this._OccuredAt = value;
            }
        }
        public IList<System.String> Targets
        {
            get
            {
                return this._Targets;
            }
            set
            {
                this._Targets = value;
            }
        }
        public int Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this._Version = value;
            }
        }
        public virtual object Get(int fieldPos)
        {
            switch (fieldPos)
            {
                case 0: return this.EntityId;
                case 1: return this.EventId;
                case 2: return this.EventType;
                case 3: return this.OccuredAt;
                case 4: return this.Targets;
                case 5: return this.Version;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
            }
            ;
        }
        public virtual void Put(int fieldPos, object fieldValue)
        {
            switch (fieldPos)
            {
                case 0: this.EntityId = (System.Guid)fieldValue; break;
                case 1: this.EventId = (System.Guid)fieldValue; break;
                case 2: this.EventType = (System.String)fieldValue; break;
                case 3: this.OccuredAt = (System.DateTime)fieldValue; break;
                case 4: this.Targets = (IList<System.String>)fieldValue; break;
                case 5: this.Version = (System.Int32)fieldValue; break;
                default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
            }
            ;
        }
    }
}
