syntax = "proto3";
package ECK1.IntegrationContracts.Kafka.IntegrationRecords.Task.Generated;
import "protobuf-net/bcl.proto"; // schema for protobuf-net's handling of core .NET types

message TaskFullRecord {
   .bcl.Guid TaskId = 1; // default value could not be applied: 00000000-0000-0000-0000-000000000000
   string Title = 2;
   string Description = 3;
   TaskItemStatus Status = 4;
   TaskItemPriority Priority = 5;
   string Assignee = 6;
   optional .bcl.DateTime DueDateUtc = 7;
   repeated TaskTag Tags = 8;
   .bcl.DateTime CreatedAt = 9;
   bool IsDeleted = 10;
   int32 Version = 11;
   .bcl.DateTime OccuredAt = 12;
}
enum TaskItemPriority {
   Low = 0;
   Medium = 1;
   High = 2;
   Critical = 3;
}
enum TaskItemStatus {
   ToDo = 0;
   InProgress = 1;
   Blocked = 2;
   Done = 3;
   Cancelled = 4;
}
message TaskTag {
   string Value = 1;
}
