# yamlApplicationConfig:
#   kafka:
#     clusters:
#       - name: local
#         bootstrapServers: local-cluster-kafka-bootstrap:9092

image:
  repository: provectuslabs/kafka-ui
  tag: v0.7.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  host: kafka-ui.localhost
  tls:
    enabled: false
    secretName: ""