apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    orleans/serviceId: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      orleans/serviceId: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        rollme: {{ now | quote }}
      labels:
        app: {{ .Chart.Name }}
        # This label identifies the service to Orleans
        orleans/serviceId: {{ .Chart.Name }}

        # This label identifies an instance of a cluster to Orleans.
        # Typically, this is the same value as the previous label, or any
        # fixed value.
        # In cases where you don't use rolling deployments (for example,
        # blue/green deployments),
        # this value can allow for distinct clusters that don't communicate
        # directly with each other,
        # but still share the same storage and other resources.
        orleans/clusterId: {{ .Chart.Name }}
    spec:
      containers:
        - name: view-projector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 11111 # Orleans Silo-to-Silo
            - containerPort: 30000 # Orleans Gateway for clients
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            - name: MongoDb__ConnectionString
              value: "mongodb://{{ .Chart.Name }}-mongo:{{ .Values.mongo.port }}"
            - name: MongoDb__DatabaseName
              value: eck1-queries
            - name: REDIS_CONNECTION
              value: "{{ .Chart.Name }}-redis:{{ .Values.redis.port }}"
            - name: ORLEANS_HOSTING
              value: k8s
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
              value: "120"

          volumeMounts:
            - name: kafka-client-secret
              mountPath: /etc/secrets
              readOnly: true
      volumes:
        - name: kafka-client-secret
          secret:
            secretName: kafka-client-secret
