apiVersion: v2
name: eck1-version-tracker
description: A Helm chart for ECK1 Version Tracker service
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: common-values
    version: 0.1.0
    repository: "file://../../common/helm/common-values"
