replicaCount: 1

image:
  repository: localhost:5000/queries-api
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30180

runMongo: true

mongo:
  image: mongo:6.0
  port: 27017
  nodePort: 32017
  persistence: true

env:
  ASPNETCORE_ENVIRONMENT: Development
