using Microsoft.CodeAnalysis;
using System.Text;

using static ECK1.CodeGen.Shared.Common.Common;
using static ECK1.CodeGen.Shared.Grpc.GrpcCommon;

namespace ECK1.GrpcService.Service.CodeGen;

[Generator]
public class ServiceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var symbolCollection = GetTypesForCodeGenWithDepsByInterface(context, InterfaceName);

        var compilation = context.CompilationProvider;

        context.RegisterSourceOutput(compilation.Combine(symbolCollection), (spc, data) =>
        {
            try
            {
                var (comp, symbols) = data;

                if (!symbols.Any())
                    return;

                var existing = comp.GetTypeByMetadataName($"{NsPrefix}.Generated.EntityStoreGrpcService");

                if (existing != null)
                    return;

                GenerateService(spc, symbols);
                GenerateConfigurator(spc, symbols);

                spc.ReportDiagnostic(Diagnostic.Create(
                    new DiagnosticDescriptor(
                        id: "GEN001",
                        title: "Generator Executed",
                        messageFormat: $"Service executed. Found {symbols.Count()} classes.",
                        category: "Generator",
                        DiagnosticSeverity.Warning,
                        isEnabledByDefault: true),
                    Location.None));


                spc.AddSource("BuildTimeInfo.Service.g.cs", $"// Generated at {DateTime.Now}");
            }
            catch (Exception e)
            {
                spc.AddSource("Exception.Service.g.cs", "// <auto-generated/>\n\n" + e);
            }
        });
    }

    private void GenerateService(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Grpc.Core;");
        sb.AppendLine("using ProtoBuf;");
        sb.AppendLine($"using {NsPrefix}.CommonDto.Generated;");
        sb.AppendLine();
        sb.AppendLine($"namespace {NsPrefix}.Generated;");
        sb.AppendLine();
        sb.AppendLine("// Auto-generated");

        sb.AppendLine();

        sb.AppendLine("[ProtoContract]");
        sb.AppendLine("public class EntityEntry<T>");
        sb.AppendLine("{");
        sb.AppendLine("    [ProtoMember(1)]");
        sb.AppendLine("    public int Version { get; init; }");
        sb.AppendLine();
        sb.AppendLine("    [ProtoMember(2)]");
        sb.AppendLine("    public T Item { get; init; } = default!;");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public interface IEntityStore");
        sb.AppendLine("{");
        sb.AppendLine("    void ClearAll();");
        sb.AppendLine();
        sb.AppendLine("    EntityEntry<T> Get<T>(string key, int minVersion) where T : class;");
        sb.AppendLine();
        sb.AppendLine("    void Put<T>(string key, int version, T obj) where T : class;");
        sb.AppendLine("}");
        sb.AppendLine();

        sb.AppendLine("public partial class EntityStoreGrpcService(IEntityStore store, ILogger<EntityStoreGrpcService> logger): IEntityStoreGrpcService");
        sb.AppendLine("{");

        foreach (var t in symbols)
        {
            try
            {
                sb
                    .AppendLine()
                    .AppendLine(GenerateServiceActionForType(t));
            }
            catch (Exception ex)
            {
                spc.AddSource($"Service_ERR_{Guid.NewGuid():N}.g.cs",
                    $"// Service generator failed for {t?.ToDisplayString()}: {ex}");
            }
        }

        sb.AppendLine("    private async ValueTask<TRes> GetEntity<TReq, TRes>(TReq request, Func<Task<TRes>> executeAsync)");
        sb.AppendLine("    {");
        sb.AppendLine("        ArgumentNullException.ThrowIfNull(request);");
        sb.AppendLine();
        sb.AppendLine("        try");
        sb.AppendLine("        {");
        sb.AppendLine("            TRes response = await executeAsync();");
        sb.AppendLine();
        sb.AppendLine("            return response;");
        sb.AppendLine("        }");
        sb.AppendLine("        catch (Exception ex)");
        sb.AppendLine("        {");
        sb.AppendLine("            logger.LogError(ex, \"gRPC GetEntity failed for {requestType}:{request}\", request.GetType(), request);");
        sb.AppendLine("            throw new RpcException(new Status(StatusCode.Internal, \"Internal server error\"));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine();
        sb.AppendLine("}");

        spc.AddSource("EntityStoreGrpc.Service.g.cs", sb.ToString());
    }

    private string GenerateServiceActionForType(INamedTypeSymbol classSymbol)
    {
        var sb = new StringBuilder();

        var safeId = MakeSafeIdentifier(classSymbol);
        var typeText = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"    public ValueTask<EntityResponse<{typeText}>> Get_{safeId}_Entity(GetEntityRequest<{typeText}> request) =>");
        sb.AppendLine($"        GetEntity(request, () =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var entityEntry = store.Get<{typeText}>(request.Id, request.MinVersion);");
        sb.AppendLine();
        sb.AppendLine($"            if (entityEntry is null)");
        sb.AppendLine("            {");
        sb.AppendLine($@"                logger.LogWarning(""EntityEntry is missing in Cache ({{type}}: {{id}})"", ""{typeText}"", request.Id);");
        sb.AppendLine($"                return Task.FromResult(new EntityResponse<{typeText}>");
        sb.AppendLine("                {");
        sb.AppendLine("                    Item = null,");
        sb.AppendLine("                    FieldMaskHash = null,");
        sb.AppendLine("                    Version = 0");
        sb.AppendLine("                });");
        sb.AppendLine("            }");
        sb.AppendLine();
        sb.AppendLine($"            var (maskedItem, maskHash) = {NsPrefix}.FieldMask.Generated.FieldMaskApplier_{safeId}.ApplyRoot(");
        sb.AppendLine($"                   entityEntry.Item, request.Mask?.Paths, request.FieldMaskHash);");
        sb.AppendLine();
        sb.AppendLine($"            return Task.FromResult(new EntityResponse<{typeText}>");
        sb.AppendLine("            {");
        sb.AppendLine("                Item = maskedItem,");
        sb.AppendLine("                FieldMaskHash = maskHash,");
        sb.AppendLine("                Version = entityEntry.Version");
        sb.AppendLine("            });");
        sb.AppendLine("        });");

        sb.AppendLine();

        return sb.ToString();
    }

    private void GenerateConfigurator(SourceProductionContext spc, IEnumerable<INamedTypeSymbol> symbols)
    {
        var sb = new StringBuilder();

        sb.AppendLine($"using {NsPrefix}.Generated;");
        sb.AppendLine($"using {NsPrefix}.CommonDto.Generated;");
        sb.AppendLine();
        sb.AppendLine($"namespace {NsPrefix}.Configuration.Generated;");
        sb.AppendLine();
        sb.AppendLine("// Auto-generated");
        sb.AppendLine("public static class ServerConsumerConfigurator");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddEventConsumers(AbstractServerConsumerConfigurator config)");
        sb.AppendLine("    {");

        foreach (var t in symbols)
        {
            try
            {
                AppendConfigActionForType(t, sb);
            }
            catch (Exception ex)
            {
                spc.AddSource($"ServerConsumerConfigurator_ERR_{Guid.NewGuid():N}.g.cs",
                    $"// Service generator failed for {t?.ToDisplayString()}: {ex}");
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public abstract class AbstractServerConsumerConfigurator");
        sb.AppendLine("{");
        sb.AppendLine("    public abstract void SetupConsumer<TContract>()");
        sb.AppendLine($"        where TContract : class, {InterfaceName};");
        sb.AppendLine("}");

        spc.AddSource("EntityStoreGrpc.ServerConsumerConfigurator.g.cs", sb.ToString());
    }

    private void AppendConfigActionForType(INamedTypeSymbol classSymbol, StringBuilder sb)
    {
        var typeText = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        sb.AppendLine($"        config.SetupConsumer<{typeText}>();");
    }
}
