replicaCount: 1

image:
  repository: localhost:5000/eck1-fe
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: app.localhost
  ingressClassName: nginx

gateway:
  host: eck1-gateway

testplatform:
  host: eck1-testplatform
