ElasticSearchConfig__ClusterUrl: https://elasticsearch-svc.elasticsearch.svc.cluster.local:9200
clickhouse:
  compress: "False"

redis:
  serviceName: "eck1-redis"
  port: 6379

helmChartRegistry: "localhost:5000"
dockerRegistry: "localhost:5000"

envSpecific:
  ELASTICSEARCH_PASSWORD: "local"