replicaCount: 1

image:
  repository: localhost:5000/commands-api
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30080

env:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: "Server=192.168.88.254,1433;Database=ECK1.Commands;User Id=sa;Password=12345;TrustServerCertificate=True"
