{{- range .Values.kafkaTopics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  namespace: kafka
  labels:
    strimzi.io/cluster: {{ $.Values.environment }}-cluster
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicationFactor }}
  config:
{{- range $key, $value := .config }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
---
{{- end }}
