replicaCount: 1

image:
  repository: localhost:5000/gateway
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30090

ingress:
  enabled: true
  host: api.localhost
  ingressClassName: nginx

env:
  ASPNETCORE_ENVIRONMENT: Production

realtime:
  redisConnectionString: "eck1-redis.app-services.svc.cluster.local:6379"
  feedbackTopic: "realtime-feedback"
