apiVersion: batch/v1
kind: Job
metadata:
  name: set-global-compatibility
  namespace: apicurio
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      containers:
        - name: set-rule
          image: curlimages/curl
          command: ["sh", "-c"]
          args:
            - >
              until curl -s http://{{ .Values.service.name }}:{{ .Values.service.port }}/health/ready; do sleep 2; done &&
              curl -X POST http://{{ .Values.service.name }}:{{ .Values.service.port }}/apis/registry/v2/admin/rules
              -H "Content-Type: application/json" -d '{"config":"BACKWARD","type":"COMPATIBILITY"}'
      restartPolicy: OnFailure
