apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry
  namespace: apicurio
  labels: 
    app: apicurio-registry
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apicurio-registry
  template:
    metadata:
      labels:
        app: apicurio-registry
    spec:
      containers:
        - name: apicurio
          image: apicurio/apicurio-registry-kafkasql:2.5.8.Final
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: REGISTRY_LOG_LEVEL
              value: INFO
            - name: LOG_LEVEL
              value: INFO
            - name: QUARKUS_PROFILE
              value: prod
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.kafka.bootstrapServers }}
            - name: REGISTRY_UI_CONFIG_APIURL
              value: "http://registry.localdev.me" 
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 30
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 20
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
