apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio-registry-operator
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apicurio-registry-operator
  template:
    metadata:
      labels:
        app: apicurio-registry-operator
    spec:
      serviceAccountName: apicurio-registry-operator
      containers:
        - name: operator
          image: {{ .Values.image.operator }}
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: apicurio-registry-operator
            - name: REGISTRY_VERSION
              value: {{ .Values.image.registryVersion }}
            - name: REGISTRY_IMAGE_KAFKASQL
              value: {{ .Values.image.registry }}:{{ .Values.image.registryVersion }}

