apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: apicurio
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: apicurio-registry
