name: Download Secrets
inputs:
  doppler-token:
    description: "Doppler service token"
    required: true
  project:
    description: "Doppler project name"
    required: true
  config:
    description: "Doppler config name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Doppler CLI
      uses: dopplerhq/cli-action@v3

    - name: Fetch secrets from Doppler
      run: |
        doppler secrets download \
          --project ${{ inputs.project }} \
          --config ${{ inputs.config }} \
          --no-file \
          --format env > doppler.env
      env:
        DOPPLER_TOKEN: ${{ inputs.doppler-token }}
      shell: bash

    - name: Show loaded secret keys
      run: |
        echo "✅ Loaded Doppler secrets:"
        cut -d '=' -f 1 doppler.env | sort
      shell: bash

    - name: Export Doppler secrets
      run: |
        while IFS= read -r line; do
          echo "$line" >> $GITHUB_ENV
        done < doppler.env
      shell: bash
