name: Run Generator
description: Iteratively call generator script for a list of schemas
inputs:
  eck1-contracts-assembly-path:
    type: string
    required: true
  eck1-integration-contracts-assembly-path:
    type: string
    required: true
  eck1-commands-assembly-path:
    type: string
    required: true
  eck1-reconciliation-contracts-assembly-path:
    type: string
    required: true
  eck1-realtime-feedback-contracts-assembly-path:
    type: string
    required: true
  schema-backup-path:
    type: string
    required: true
  solution-file:
    type: string
    required: true
  solution-dir:
    type: string
    required: true
  schema-root:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare schema-gen-job-params.json
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Path "/tmp/evolve-schema" -Force | Out-Null

        $content = Get-Content "${{ github.action_path }}/schema-gen-job-params.json" -Raw
        $content = $content -replace "__ECK1_CONTRACTS_ASSEMBLY_PATH__", "${{ inputs.eck1-contracts-assembly-path }}"
        $content = $content -replace "__ECK1_INTEGRATION_CONTRACTS_ASSEMBLY_PATH__", "${{ inputs.eck1-integration-contracts-assembly-path }}"
        $content = $content -replace "__ECK1_COMMANDS_ASSEMBLY_PATH__", "${{ inputs.eck1-commands-assembly-path }}"
        $content = $content -replace "__ECK1_RECONCILIATION_CONTRACTS_ASSEMBLY_PATH__", "${{ inputs.eck1-reconciliation-contracts-assembly-path }}"
        $content = $content -replace "__ECK1_REALTIME_FEEDBACK_CONTRACTS_ASSEMBLY_PATH__", "${{ inputs.eck1-realtime-feedback-contracts-assembly-path }}"
        $content = $content -replace "__SOLUTION_DIR__", "${{ inputs.solution-dir }}"
        $content | Out-File "/tmp/evolve-schema/params.json" -Encoding utf8

    - name: Call evolve_schema
      uses: clark1992/kafka-schema-generator/.github/actions/evolve-schema@stable-v1
      with:
        params-file: "/tmp/evolve-schema/params.json"
