name: Run Generator
description: Iteratively call generator script for a list of schemas
inputs:
  assembly-path:
    type: string
    required: true
  schema-backup-path:
    type: string
    required: true
  solution-path:
    type: string
    required: true
  schema-root:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare schema-gen-job-params.json
      shell: pwsh
      run: |
        $content = Get-Content "${{ github.action_path }}/schema-gen-job-params.json" -Raw
        $content = $content -replace "__ASSEMBLY_PATH__", "${{ inputs.assembly-path }}"
        $content = $content -replace "__SCHEMA_TO_COMPARE_PATH__", "${{ inputs.schema-backup-path }}"
        $content = $content -replace "__SCHEMA_ROOT__", "${{ inputs.schema-root }}"
        $content | Out-File "/tmp/evolve-schema/params.json" -Encoding utf8

        Write-Host "AFTER content:"
        Write-Host $content

    - name: Call evolve_schema
      uses: clark1992/kafka-schema-generator/.github/actions/evolve-schema@stable-v1
      with:
        params-file: "/tmp/evolve-schema/params.json"

    - name: Update solution with generated files
      run: .github/scripts/update-sln.ps1 ${{ inputs.solution-path }} ${{ inputs.schema-root }}
      working-directory: src
      shell: pwsh