name: Run Generator
description: Iteratively call generator script for a list of schemas
inputs:
  assembly-path:
    type: string
    required: true
  schema-backup-path:
    type: string
    required: true
  solution-file:
    type: string
    required: true
  solution-dir:
    type: string
    required: true
  schema-root:
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare schema-gen-job-params.json
      shell: pwsh
      run: |
        mkdir "/tmp/evolve-schema" -Force

        $content = Get-Content "${{ github.action_path }}/schema-gen-job-params.json" -Raw
        $content = $content -replace "__ASSEMBLY_PATH__", "${{ inputs.assembly-path }}"
        $content = $content -replace "__SOLUTION_DIR__", "${{ inputs.solution-dir }}"
        $content | Out-File "/tmp/evolve-schema/params.json" -Encoding utf8

    - name: Call evolve_schema
      uses: clark1992/kafka-schema-generator/.github/actions/evolve-schema@stable-v1
      with:
        params-file: "/tmp/evolve-schema/params.json"
