using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace ECK1.AsyncApi.CodeGen;

[Generator]
public sealed class CommandRegistrationGenerator : IIncrementalGenerator
{
    private const string CommandAttributeName = "ECK1.AsyncApi.Attributes.CommandAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandInterfaces = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                CommandAttributeName,
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: static (ctx, _) => ExtractCommandInfo(ctx))
            .Where(static info => info != null);

        var collected = commandInterfaces.Collect();

        context.RegisterSourceOutput(collected, static (spc, commands) => GenerateSource(spc, commands));
    }

    private static CommandInfo ExtractCommandInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol)
            return null;

        var topicAttr = symbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass != null
                && a.AttributeClass.ContainingNamespace != null
                && a.AttributeClass.Name == "TopicAttribute"
                && a.AttributeClass.ContainingNamespace.ToDisplayString() == "ECK1.AsyncApi.Attributes");

        if (topicAttr == null)
            return null;

        string topicConfigKey = null;
        string topic = null;

        if (topicAttr.ConstructorArguments.Length >= 1 && topicAttr.ConstructorArguments[0].Value is string t)
            topic = t;
        if (topicAttr.ConstructorArguments.Length >= 2 && topicAttr.ConstructorArguments[1].Value is string tck)
            topicConfigKey = tck;

        foreach (var arg in topicAttr.NamedArguments)
        {
            if (arg.Key == "TopicConfigKey" && arg.Value.Value is string nck)
                topicConfigKey = nck;
            else if (arg.Key == "Topic" && arg.Value.Value is string nt)
                topic = nt;
        }

        if (string.IsNullOrEmpty(topicConfigKey) && string.IsNullOrEmpty(topic))
            return null;

        return new CommandInfo(
            commandType: symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            topicConfigKey: topicConfigKey,
            topic: topic);
    }

    private static void GenerateSource(SourceProductionContext spc, ImmutableArray<CommandInfo> commands)
    {
        if (commands.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();
        sb.AppendLine("namespace ECK1.AsyncApi.Generated;");
        sb.AppendLine();
        sb.AppendLine("// Auto-generated by ECK1.AsyncApi.CodeGen");
        sb.AppendLine("public static class CommandConfigurator");
        sb.AppendLine("{");
        sb.AppendLine("    public static void AddCommands(AbstractCommandConfigurator config)");
        sb.AppendLine("    {");

        foreach (var cmd in commands)
        {
            var configKeyArg = cmd.TopicConfigKey != null
                ? "\"" + Escape(cmd.TopicConfigKey) + "\""
                : "null";
            var topicArg = cmd.Topic != null
                ? "\"" + Escape(cmd.Topic) + "\""
                : "null";

            sb.AppendLine(string.Format(
                "        config.RegisterCommand<{0}>({1}, {2});",
                cmd.CommandType,
                configKeyArg,
                topicArg));
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("public abstract class AbstractCommandConfigurator");
        sb.AppendLine("{");
        sb.AppendLine("    public abstract void RegisterCommand<TCmd>(string topicConfigKey, string topic)");
        sb.AppendLine("        where TCmd : class;");
        sb.AppendLine("}");

        spc.AddSource("AsyncApi.CommandRegistrations.g.cs", sb.ToString());
    }

    private static string Escape(string s)
    {
        if (s == null) return null;
        return s.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private sealed class CommandInfo
    {
        public string CommandType { get; }
        public string TopicConfigKey { get; }
        public string Topic { get; }

        public CommandInfo(string commandType, string topicConfigKey, string topic)
        {
            CommandType = commandType;
            TopicConfigKey = topicConfigKey;
            Topic = topic;
        }
    }
}
