apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      annotations:
        rollme: {{ now | quote }}
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: GATEWAY_HOST
              value: "{{ .Values.gateway.host }}"
            - name: TESTPLATFORM_HOST
              value: "{{ .Values.testplatform.host }}"
            - name: ZITADEL_AUTHORITY
              valueFrom:
                configMapKeyRef:
                  name: global-vars
                  key: Zitadel__Issuer
            - name: ZITADEL_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: zitadel-oidc-client
                  key: client_id
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
