apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
stringData:
  Kafka__BootstrapServers: {{ .Values.kafkaBootstrapServers }}
  Kafka__SchemaRegistryUrl: {{ .Values.kafkaSchemaRegistryUrl }}
  Kafka__User: {{ .Values.kafkaUser }}
  Kafka__Secret: {{ .Values.kafkaSecret }}