replicaCount: 1

image:
  repository: localhost:5000/failed-view-rebuilder
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  nodePort: 30100

env:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__DefaultConnection: "Server=192.168.88.254,1433;Database=ECK1.FailedViewRebuilder;User Id=sa;Password=12345;TrustServerCertificate=True"
