name: Publish NuGet

on:
  workflow_call:
    inputs:
      project_path:
        description: 'Path to Project folder'
        required: true
        type: string
      csproj_file:
        description: '.csproj file name'
        required: true
        type: string
      dotnet_version:
        description: '.NET version'
        required: false
        default: '8.0.x'
        type: string

permissions:
  contents: read
  packages: write

jobs:
  nuget-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet jq libxml2-utils

      - name: Update version and repository url
        run: bash .github/scripts/update-version.sh ${{ inputs.project_path }}/${{ inputs.csproj_file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}

      - name: Restore
        working-directory: ${{ inputs.project_path }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ inputs.project_path }}
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        working-directory: ${{ inputs.project_path }}
        run: dotnet pack --configuration Release --no-build -o ./artifacts

      - name: Push to GitHub Packages
        working-directory: ${{ inputs.project_path }}
        run: |
          dotnet nuget push ./artifacts/*.nupkg \
            --source github \
            --api-key ${{ secrets.GITHUB_TOKEN }}
