name: Publish ECK1.CommonUtils

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/Nuget/ECK1.CommonUtils/**'
      - '.github/workflows/publish-nuget.common-utils.yml'
      - '.github/workflows/publish-nuget-shared.yml'
      - '.github/scripts/update-version.sh'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/publish-nuget-shared.yml
    with:
      project_path: 'Nuget/ECK1.CommonUtils'
      csproj_file: 'ECK1.CommonUtils.csproj'
