name: Publish ECK1.Kafka

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/Nuget/ECK1.Kafka/**'
      - '.github/workflows/publish-nuget.kafka.yml'
      - '.github/workflows/publish-nuget-shared.yml'
      - '.github/scripts/update-version.sh'

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/publish-nuget-shared.yml
    with:
      project_path: 'src/Nuget/ECK1.Kafka'
      csproj_file: 'ECK1.Kafka.csproj'
