name: Run Generator

on:
  workflow_call:
    inputs:
        assembly-path:
          required: true
          type: string

jobs:
  generate-schemas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        schema:
          - type-name: "ECK1.Contracts.Kafka.BusinessEvents.Sample.ISampleEvent"
            current-latest-schema-path: "/tmp/schema-backup1/BusinessEvents/Sample"
            format: "json"
            output-path: "_SolutionItems/SchemaRegistry/BusinessEvents/Sample"
    
    steps:
      - name: Run generator
        uses: clark1992/kafka-schema-generator/.github/actions/evolve-schema@stable-v1
        with:
          assembly-path: ${{ inputs.assembly-path }}
          type-name: ${{ matrix.schema.type-name }}
          current-latest-schema-path: ${{ matrix.schema.current-latest-schema-path }}
          format: ${{ matrix.schema.format }}
          output-path: ${{ matrix.schema.output-path }}

      - name: List generated files
        run: |
          echo "generated:"
          tree /_SolutionItems/SchemaRegistry
        shell: bash