{
 "title": "Global",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cardinality / Unique Entities",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "-- Cardinality / Unique Entities\r\n-- Unique entities over time\r\nWITH\r\n    toDateTime($__from / 1000) AS from_ts,\r\n    toDateTime($__to / 1000)   AS to_ts,\r\n    $__interval_s              AS step,\r\n\r\n    grid AS (\r\n        SELECT\r\n            toDateTime(generate_series - generate_series % 60) AS time\r\n        FROM generateSeries(toUInt32(from_ts), toUInt32(to_ts), step)\r\n    ),\r\n\r\n    agg AS (\r\n        SELECT\r\n            toDateTime(toUnixTimestamp(toStartOfMinute(occurred_at))) AS time,\r\n            uniqExact(tuple(entity_type, entity_id)) AS unique_entities\r\n        FROM integration_events_raw\r\n        WHERE occurred_at >= from_ts\r\n          AND occurred_at <= to_ts\r\n        GROUP BY time\r\n    )\r\n\r\nSELECT\r\n    g.time,\r\n    coalesce(a.unique_entities, 0) AS unique_entities\r\nFROM grid AS g\r\nLEFT JOIN agg AS a\r\n    ON g.time = a.time\r\nORDER BY g.time"
    },
    {
     "rawSql": "-- Cardinality / Unique Entities\r\n-- Avg events per entity\r\nWITH\r\n    toDateTime($__from / 1000) AS from_ts,\r\n    toDateTime($__to / 1000)   AS to_ts,\r\n    $__interval_s              AS step,\r\n\r\n    grid AS (\r\n        SELECT\r\n            toDateTime(generate_series - generate_series % 60) AS time\r\n        FROM generateSeries(toUInt32(from_ts), toUInt32(to_ts), step)\r\n    ),\r\n\r\n    per_entity AS (\r\n        SELECT\r\n            toDateTime(toUnixTimestamp(toStartOfMinute(occurred_at))) AS time,\r\n            tuple(entity_type, entity_id) AS entity_key,\r\n            count(*) AS events_cnt\r\n        FROM integration_events_raw\r\n        WHERE occurred_at >= from_ts\r\n          AND occurred_at <= to_ts\r\n        GROUP BY time, entity_key\r\n    ),\r\n\r\n    agg AS (\r\n        SELECT\r\n            time,\r\n            avg(events_cnt) AS avg_events_per_entity\r\n        FROM per_entity\r\n        GROUP BY time\r\n    )\r\n\r\nSELECT\r\n    g.time,\r\n    coalesce(a.avg_events_per_entity, 0) AS avg_events_per_entity\r\nFROM grid AS g\r\nLEFT JOIN agg AS a\r\n    ON g.time = a.time\r\nORDER BY g.time\r\n"
    },
    {
     "rawSql": "-- Cardinality / Unique Entities\r\n-- P95 events per entity\r\nWITH\r\n    toDateTime($__from / 1000) AS from_ts,\r\n    toDateTime($__to / 1000)   AS to_ts,\r\n    $__interval_s              AS step,\r\n\r\n    grid AS (\r\n        SELECT\r\n            toDateTime(generate_series - generate_series % 60) AS time\r\n        FROM generateSeries(toUInt32(from_ts), toUInt32(to_ts), step)\r\n    ),\r\n\r\n    per_entity AS (\r\n        SELECT\r\n            toDateTime(toUnixTimestamp(toStartOfMinute(occurred_at))) AS time,\r\n            tuple(entity_type, entity_id) AS entity_key,\r\n            count(*) AS events_cnt\r\n        FROM integration_events_raw\r\n        WHERE occurred_at >= from_ts\r\n          AND occurred_at <= to_ts\r\n        GROUP BY time, entity_key\r\n    ),\r\n\r\n    agg AS (\r\n        SELECT\r\n            time,\r\n            quantileExact(0.95)(events_cnt) AS p95_events_per_entity\r\n        FROM per_entity\r\n        GROUP BY time\r\n    )\r\n\r\nSELECT\r\n    g.time,\r\n    coalesce(a.p95_events_per_entity, 0) AS p95_events_per_entity\r\nFROM grid AS g\r\nLEFT JOIN agg AS a\r\n    ON g.time = a.time\r\nORDER BY g.time\r\n"
    }
   ]
  },
  {
   "title": "Breakdown by entity type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "WITH\r\n    toUInt32($__from / 1000) AS from_ts,\r\n    toUInt32($__to / 1000)   AS to_ts\r\n\r\nSELECT\r\n    toDateTime(grid.t) AS time,\r\n    CAST(types.entity_type AS String) AS type,\r\n    coalesce(data.events_count, 0) AS metric\r\nFROM\r\n(\r\n    /* временная сетка */\r\n    SELECT\r\n        arrayJoin(\r\n            range(\r\n                intDiv(from_ts, s.step) * s.step,\r\n                intDiv(to_ts, s.step) * s.step + s.step,\r\n                s.step\r\n            )\r\n        ) AS t\r\n    FROM\r\n    (\r\n        SELECT intDiv($__interval_ms, 1000) AS step\r\n    ) AS s\r\n) AS grid\r\nCROSS JOIN\r\n(\r\n    /* список entity_type */\r\n    SELECT DISTINCT entity_type\r\n    FROM eck1_analytics.events_per_minute_by_type_by_entity_type\r\n) AS types\r\nLEFT JOIN\r\n(\r\n    /* агрегированные данные */\r\n    SELECT\r\n        intDiv(toUInt32(minute), s.step) * s.step AS t,\r\n        entity_type,\r\n        sum(events_count) AS events_count\r\n    FROM eck1_analytics.events_per_minute_by_type_by_entity_type\r\n    CROSS JOIN\r\n    (\r\n        SELECT intDiv($__interval_ms, 1000) AS step\r\n    ) AS s\r\n    WHERE minute >= toDateTime($__from / 1000)\r\n      AND minute <= toDateTime($__to / 1000)\r\n    GROUP BY\r\n        t,\r\n        entity_type\r\n) AS data\r\nON grid.t = data.t\r\nAND types.entity_type = data.entity_type\r\nORDER BY\r\n    time,\r\n    metric\r\n"
    }
   ]
  },
  {
   "title": "Events Over Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH\r\n    $__interval_s AS step,\r\n    toUInt32($__from/ 1000) AS from_ts,\r\n    toUInt32($__to / 1000) AS to_ts\r\n\r\nSELECT\r\n    toDateTime(t) AS time,\r\n    coalesce(sum(events_count), 0) AS count\r\nFROM\r\n(\r\n    SELECT\r\n        arrayJoin(\r\n            range(\r\n                intDiv(from_ts, step) * step,\r\n                intDiv(to_ts, step) * step + step,\r\n                step\r\n            )\r\n        ) AS t\r\n) grid\r\nLEFT JOIN\r\n(\r\n    SELECT\r\n        intDiv(toUInt32(minute), step) * step AS t,\r\n        sum(events_count) AS events_count\r\n    FROM \"eck1_analytics\".\"events_per_minute_by_type_by_entity_type\"\r\n    WHERE  ( time >= $__fromTime AND time <= $__toTime )\r\n    GROUP BY t\r\n) data\r\nUSING t\r\nGROUP BY t\r\nORDER BY t\r\n"
    }
   ]
  }
 ]
}