{
 "title": "Logs/Traces",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "service_name",
    "query": {
     "query": "label_values(process_cpu_count{k8s_namespace_name=\"app-services\"},service_name)"
    }
   },
   {
    "name": "env",
    "query": {
     "query": "label_values(process_cpu_count,deployment_environment)"
    }
   },
   { "name": "ts", "label": "ts" },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=\"app-services\"},pod)"
    }
   },
   { "name": "ns", "label": "ns", "query": "app-services" },
   {
    "name": "log_service_name",
    "label": "log_service_name",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"app-services\"},label_service_name)"
    }
   },
   { "name": "interval", "label": "interval", "query": "15s,30s,1m,2m,5m" }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by (namespace, pod) (\r\n    container_memory_working_set_bytes{\r\n      namespace=\"$ns\",\r\n      pod=~\"$pod\",\r\n      pod!~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\",\r\n      container!=\"\",\r\n      container!=\"POD\"\r\n    }\r\n  )\r\n)\r\n/\r\nclamp_min(\r\n  sum by (namespace, pod) (\r\n    kube_pod_container_resource_limits{\r\n      namespace=\"$ns\",\r\n      pod=~\"$pod\",\r\n      resource=\"memory\",\r\n      unit=\"byte\"\r\n    }\r\n  ),\r\n  1\r\n)\r\n* on (namespace, pod) group_left(label_app)\r\n    kube_pod_labels{\r\n      namespace=\"$ns\",\r\n      label_service_name=~\"$service_name\",\r\n      pod=~\"$pod\",\r\n      pod!~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\"\r\n    }",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n    rate(container_network_receive_bytes_total{\r\n        namespace=\"$ns\",\r\n        pod=~\"$pod\", \r\n        container=\"POD\",\r\n        container_label_service_name=~\"$service_name\",\r\n        container_label_service_name=~\"$log_service_name\",\r\n        container_label_environment=~\"$env\",\r\n        interface=\"eth0\"\r\n    }\r\n    [$__rate_interval]\r\n    )\r\n)",
     "legendFormat": "{{pod}} (receive)"
    },
    {
     "expr": "sum by (pod) (\r\n    rate(container_network_transmit_bytes_total{\r\n        namespace=\"$ns\",\r\n        pod=~\"$pod\", \r\n        container=\"POD\",\r\n        container_label_service_name=~\"$service_name\",\r\n        container_label_service_name=~\"$log_service_name\",\r\n        container_label_environment=~\"$env\",\r\n        interface=\"eth0\"\r\n    }\r\n    [$__rate_interval]\r\n    )\r\n) * -1",
     "legendFormat": "{{pod}} (send)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by (pod, namespace) (\r\n    rate(\r\n      container_cpu_usage_seconds_total{\r\n        namespace=\"$ns\",\r\n        pod=~\"$pod\",\r\n        pod!~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\",\r\n        container!=\"\",\r\n        container!=\"POD\"\r\n      }[$__rate_interval]\r\n    )\r\n  )\r\n  * on (pod, namespace)\r\n    group_left(label_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"$ns\",\r\n      label_service_name=~\"$service_name\",\r\n      label_environment=~\"$env\",\r\n      pod=~\"$pod\",\r\n      pod!~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\"\r\n    }\r\n  /\r\n  ignoring(label_service_name)\r\n  sum by (pod, namespace) (\r\n    kube_pod_container_resource_limits{\r\n      namespace=\"$ns\",\r\n      pod=~\"$pod\",\r\n      pod!~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\",\r\n      resource=\"cpu\",\r\n      unit=\"core\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "{{pod}} (%)"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\r\n    rate(container_fs_reads_bytes_total{\r\n        namespace=\"$ns\",\r\n        pod=~\"$pod\",\r\n        container!=\"POD\",\r\n        container!=\"\"\r\n    }\r\n    [$__rate_interval])\r\n)\r\n* on (namespace, pod) \r\n  group_left(label_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"$ns\",\r\n      label_service_name=~\"$service_name\",\r\n      label_service_name=~\"$log_service_name\",\r\n      label_environment=~\"$env\",\r\n      pod=~\"$pod\"\r\n    }",
     "legendFormat": "{{pod}} (read)"
    },
    {
     "expr": "sum by (namespace, pod) (\r\n    rate(container_fs_writes_bytes_total{\r\n        namespace=\"$ns\",\r\n        pod=~\"$pod\", \r\n        container!=\"POD\",\r\n        container!=\"\"\r\n    }\r\n    [$__rate_interval]\r\n    )\r\n)\r\n* on (namespace, pod) \r\n  group_left(label_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"$ns\",\r\n      label_service_name=~\"$service_name\",\r\n      label_service_name=~\"$log_service_name\",\r\n      label_environment=~\"$env\",\r\n      pod=~\"$pod\"\r\n    }\r\n* -1",
     "legendFormat": "{{pod}} (write)"
    }
   ]
  },
  {
   "title": "DB CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by (namespace, pod) (\r\n    rate(\r\n      container_cpu_usage_seconds_total{\r\n        namespace=\"$ns\",\r\n        pod=~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\"\r\n      }[$__rate_interval]\r\n    )\r\n  )\r\n  /\r\n  on (namespace, pod)\r\n  group_left(label_service_name)\r\n  sum by (namespace, pod) (\r\n    kube_pod_container_resource_limits{\r\n      namespace=\"$ns\",\r\n      pod=~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\",\r\n      resource=\"cpu\",\r\n      unit=\"core\"\r\n    }\r\n  )\r\n)\r\n* on (namespace, pod)\r\n  group_left(label_service_name)\r\n  kube_pod_labels{\r\n    namespace=\"$ns\",\r\n    pod=~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\",\r\n    label_service_name=~\".*$log_service_name.*\",\r\n    label_service_name=~\"$service_name\",\r\n    label_environment=~\"$env\"\r\n  }\r\n",
     "legendFormat": "{{pod}} ({{label_service_name}})"
    }
   ]
  },
  {
   "title": "DB Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  sum by (namespace, pod) (\r\n    container_memory_working_set_bytes{\r\n      namespace=\"$ns\",\r\n      pod=~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\"\r\n    }\r\n  )\r\n)\r\n/\r\nclamp_min(\r\n  sum by (namespace, pod) (\r\n    kube_pod_container_resource_limits{\r\n      namespace=\"$ns\",\r\n      pod=~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\",\r\n      resource=\"memory\",\r\n      unit=\"byte\"\r\n    }\r\n  ),\r\n  1\r\n)\r\n* on(namespace, pod)\r\ngroup_left(label_service_name)\r\nkube_pod_labels{\r\n  namespace=\"$ns\",\r\n  pod=~\".*-sql.*|.*-mongo.*|.*-redis.*|.*-clickhouse.*\",\r\n  label_service_name=~\".*$log_service_name.*\",\r\n  label_service_name=~\"$service_name\",\r\n  label_environment=~\"$env\"\r\n}\r\n",
     "legendFormat": "{{pod}} ({{label_service_name}})"
    }
   ]
  },
  {
   "title": "SQL Lock Wait Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "sum by (service_name) (sqlserver_lock_wait_rate_per_second{service_name=~\"$service_name\", service_name=~\".*$log_service_name.*\",deployment_environment=\"$env\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "SQL Deadlocks / Waits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "sum by (service_name) (sqlserver_deadlock_rate_per_s{service_name=~\"$service_name\", deployment_environment=\"$env\"})",
     "legendFormat": "{{service_name}} deadlocks/s"
    },
    {
     "expr": "sum by (service_name, wait_category) (rate(sqlserver_os_wait_duration_seconds_total{service_name=~\"$service_name\", deployment_environment=\"$env\"}[$__rate_interval]))",
     "legendFormat": "{{service_name}} {{wait_category}} wait s/s"
    }
   ]
  },
  {
   "title": "Logs Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (detected_level) (\r\n  count_over_time({service_name=~\"$service_name\", service_name!=\"unknown_service\", deployment_environment=\"$env\", k8s_pod_name=~\"$pod\"} | logfmt | detected_level!=\"\" [$__interval])\r\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\", service_name!=\"unknown_service\", deployment_environment=\"$env\", k8s_pod_name=~\"$pod\"}\r\n| logfmt"
    },
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\", service_name!=\"unknown_service\", deployment_environment=\"$env\", k8s_pod_name=\"\"}\r\n| logfmt"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "filters": [
      { "id": "96453b8c", "operator": "=", "scope": "span" }
     ],
     "limit": 200,
     "metricsQueryType": "range",
     "query": "{resource.service.name=~\"$service_name\" && resource.service.name!=\"unknown_service\" && resource.k8s.pod.name=~\"$pod\" && resource.deployment.environment=\"$env\"}",
     "spss": 30,
     "tableType": "traces"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "SQL Page Life Expectancy",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service_name, performance_counter_object_name) (sqlserver_page_life_expectancy_seconds{service_name=~\"$service_name\", service_name=~\"$log_service_name\", deployment_environment=\"$env\"})",
     "legendFormat": "{{service_name}} ({{performance_counter_object_name}})"
    }
   ]
  },
  {
   "title": "SQL Batch Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops/s" } },
   "targets": [
    {
     "expr": "sum by (service_name) (sqlserver_batch_request_rate_per_second{service_name=~\"$service_name\", service_name=~\"$log_service_name\",deployment_environment=\"$env\"})",
     "legendFormat": "{{service_name}}"
    }
   ]
  }
 ]
}