{
 "title": "OpenTelemetry dotnet webapi",
 "description": "OpenTelemetry .Net (dotnet) ASP.NET using RED and USE method",
 "tags": [
  "loki",
  "mimir",
  "otlp",
  "opentelemetry",
  "asp.net",
  "dotnet"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "prom_ds", "query": "prometheus" },
   { "name": "loki_ds", "query": "loki" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count,service_name)"
    }
   },
   {
    "name": "deployment_environment",
    "label": "Deployment Environment",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count{service_name=\"$service_name\"},deployment_environment)"
    }
   },
   {
    "name": "service_version",
    "label": "Service version",
    "query": {
     "query": "label_values(process_runtime_dotnet_assemblies_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"},service_version)"
    }
   },
   {
    "name": "host_name",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", service_version=\"$service_version\"},host_name)"
    }
   },
   {
    "name": "http_route",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", service_version=\"$service_version\", host_name=~\"$host_name\"},http_route)"
    }
   },
   {
    "name": "http_response_status_code",
    "query": {
     "query": "label_values(http_server_request_duration_seconds_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", service_version=\"$service_version\", host_name=~\"$host_name\", http_route=~\"$http_route\"},http_response_status_code)"
    }
   },
   { "name": "top", "label": "Top", "query": "1, 5, 10" },
   { "name": "percentile", "query": "p95 : 0.95, p50 : 0.50" }
  ]
 },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(process_runtime_dotnet_exceptions_count_total{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\", deployment_environment=~\"$deployment_environment\"} | severity_text=\"Error\""
    }
   ]
  },
  {
   "title": "Rates",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by (http_response_status_code) (rate(http_server_request_duration_seconds_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "heatmap",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-httpserverrequestduration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "RED", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Http Server requests Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by (host_name,http_request_method,http_route,url_scheme,http_response_status_code) (rate(http_server_request_duration_seconds_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}}"
    }
   ]
  },
  {
   "title": "Http Server requests Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(${top}, \r\n    sum by(host_name, url_scheme, http_request_method, http_route, http_response_status_code, error_type) (rate(http_server_request_duration_seconds_count{service_name=\"${service_name}\", service_version=\"${service_version}\", deployment_environment=\"${deployment_environment}\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code!~\"[1-3]..\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval]))\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}} {{error_type}}"
    }
   ]
  },
  {
   "title": "Http Server requests Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(http_server_request_duration_seconds_bucket{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", host_name=~\"${host_name}\", http_route=~\"${http_route}\", http_response_status_code=~\"${http_response_status_code}\"}[$__rate_interval])) by (le, http_request_method, url_scheme, host_name, http_route, http_response_status_code)\r\n    )\r\n)",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}{{http_route}}: {{http_response_status_code}}"
    }
   ]
  },
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "In-flight HTTP requests",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-httpserveractive_requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host_name, http_request_method, url_scheme) (rate(http_server_active_requests{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "{{http_request_method}} {{url_scheme}}://{{host_name}}"
    }
   ]
  },
  {
   "title": "Routing match attempts",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-aspnetcoreroutingmatch_attempts",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (host_name,http_route,aspnetcore_routing_is_fallback) (rate(aspnetcore_routing_match_attempts_total{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", aspnetcore_routing_match_status!=\"success\" }[$__rate_interval]))",
     "legendFormat": "{{host_name}}{{http_route}} failure (fallback:{{aspnetcore_routing_is_fallback}})"
    },
    {
     "expr": "sum by (host_name,http_route) (rate(aspnetcore_routing_match_attempts{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", aspnetcore_routing_match_status=\"success\", aspnetcore_routing_is_fallback=\"true\" }[$__rate_interval]))",
     "legendFormat": "{{host_name}}{{http_route}} fallback route"
    },
    {
     "expr": "sum by (host_name,http_route) (rate(aspnetcore_routing_match_attempts{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\", aspnetcore_routing_match_status=\"success\", aspnetcore_routing_is_fallback=\"false\" }[$__rate_interval]))",
     "legendFormat": "{{host_name}}{{http_route}} success"
    }
   ]
  },
  {
   "title": "Active connections (kestrel)",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-kestrelactive_connections",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (network_type, network_transport, server_address, server_port) (max_over_time(kestrel_active_connections{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__interval]))",
     "legendFormat": "{{network_type}} {{network_transport}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  {
   "title": "Queued connections (kestrel)",
   "type": "timeseries",
   "description": "https://learn.microsoft.com/en-us/dotnet/core/diagnostics/built-in-metrics-aspnetcore#metric-kestrelqueued_connections",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (network_type, network_transport, server_address, server_port) (max_over_time(kestrel_queued_connections{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__interval]))",
     "legendFormat": "{{network_type}} {{network_transport}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  {
   "title": "Connections Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(kestrel_connection_duration_seconds_bucket{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval])) by (le,network_protocol_name,network_protocol_version,network_transport,network_type,server_address,server_port)\r\n    )\r\n)",
     "legendFormat": "{{network_type}} {{network_transport}}/{{network_protocol_name}}{{network_protocol_version}} {{server_address}}:{{server_port}}"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (state) (rate(process_cpu_time_seconds_total{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(process_memory_usage_bytes{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "title": "Process Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(process_thread_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "Process Threads"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "GC Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(process_runtime_dotnet_gc_committed_memory_size_bytes{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "GC Commited Memory Size"
    },
    {
     "expr": "max(max_over_time(process_runtime_dotnet_gc_objects_size{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "GC Objects size"
    },
    {
     "expr": "sum(rate(process_runtime_dotnet_gc_allocations_size{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "GC Allocation Size"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (generation) (max_over_time(process_runtime_dotnet_gc_heap_size_bytes{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Heap Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (generation) (max_over_time(process_runtime_dotnet_gc_heap_fragmentation_size_bytes{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (generation) (rate(process_runtime_dotnet_gc_collections_count_total{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(process_runtime_dotnet_exceptions_count_total{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "Exceptions"
    }
   ]
  },
  {
   "title": "Thread Pool Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(process_runtime_dotnet_thread_pool_threads_count{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "Thead Pool Threads"
    }
   ]
  },
  {
   "title": "Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(max_over_time(process_runtime_dotnet_thread_pool_queue_length{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval]))",
     "legendFormat": "Thread Pool Queue Length"
    }
   ]
  },
  { "title": "HTTP Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (http_connection_state, server_address, server_port, url_scheme, network_protocol_version) (max_over_time(http_client_open_connections{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__interval]))",
     "legendFormat": "{{http_connection_state}} {{server_address}}:{{server_port}} {{url_scheme}}{{network_protocol_version}}"
    }
   ]
  },
  {
   "title": "Http Client requests Durations ($percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "repeat": "percentile",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk($top, \r\n    histogram_quantile(${percentile:value}, \r\n        sum(rate(http_client_request_duration_seconds_bucket{service_name=\"$service_name\", deployment_environment=\"$deployment_environment\"}[$__rate_interval])) by (le, http_request_method, url_scheme, http_route, http_response_status_code,server_address,server_port,network_protocol_version)\r\n    )\r\n)",
     "legendFormat": "{{url_scheme}}/{{network_protocol_version}} {{server_address}}:{{server_port}} {{http_request_method}}: {{http_response_status_code}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "type": "logs",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 106 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$service_name\", deployment_environment=~\"$deployment_environment\"} |= ``"
    }
   ]
  }
 ]
}